### ISSUE TITLE
Block API v3 Feedback

### ISSUE THREAD

**Issue by jaymcp** [amnestywebsite/humanity-theme#559]
Feedback to be addressed:

> Testing notes
> 
> - Action Block: Image appears distorted in the editor, button styles are incorrect (width and padding) for both editor and frontend, regardless of branding plugin activity. Alignment controls have no affect on the front end, and float in the editor
> - Background Media BLOCK: does not render correctly and breaks when trying to add a BG image.
> - Background Media PATTERN: no top padding on column inner blocks (frontend) 
> - Blockquote: core quote still hidden and missing styles, previous PR for reference: https://github.com/amnestywebsite/humanity-theme/pull/326
> - Buttons: Back link styles don't apply on the frontend, all buttons are pill shaped on the frontend. Default style when inserting button is off http://bigbite.im/i/6gwWem
> - Collapsable/Details: details styles appear to be part of this PR (compare to original PR [here](https://github.com/amnestywebsite/humanity-theme/pull/240), but do not seem to be applying at all http://bigbite.im/i/1iSWPw) 
> - Columns: custom columns block still insertable in the block inserter
> - Countdown Timer: inspector controls looking a little wonky http://bigbite.im/i/La52p2
> - Custom card pattern: button expands outside the card in the editor, image covers, but image position might need addressing (http://bigbite.im/i/dkYtCB)
> - Resource Download: No padding on button, and block styles labelled incorrectly (http://bigbite.im/i/OejEbr), core/file is available in the block inserter, not sure if this should be hidden
> - Fluid iFrame: seems to be missing button styles in the editor
> - iFrame Button: nothing happens when clicking the button on the frontend, and dark styles seem to be missing frontend too
> - Links with Icons Patterns: all buttons are justified to the left rather than the centre, square border style is missing, also has brand styles that I don't think belong on there (http://bigbite.im/i/bVwFgq)
> - Menu Block: struggles to load menus making the block unusable (http://bigbite.im/v/44QVSQ)
> - Regions: works as expected, but some changes are a step behind in the editor, namely changing taxonomy and subregions toggle
> - Related Content: block breaks as soon as it is inserted into a post
> - Slider block: block breaks as soon as it is inserted into a post
> - Tweet Action: alternative style has no effect in the editor, Size dropdown appears to have no effect anywhere.
> - Modal CTA: when opening the modal on the frontend, the entire contents of the dropdown is displayed (http://bigbite.im/i/k9qyLZ)
> - Sidebar block: don't seem to be able to get the sidebar block to render on the front end
> - Recipients block: dropdown displays over other content on the front end 

 _Originally posted by @Gentyspun in [#285](https://github.com/amnestywebsite/humanity-theme/issues/285#issuecomment-2724226559)_

**Comment by jaymcp** [comment]
> Action Block: Image appears distorted in the editor, button styles are incorrect (width and padding) for both editor and frontend, regardless of branding plugin activity. Alignment controls have no affect on the front end, and float in the editor

button styles were not marked as shared. resolved.
`.editor-plain-text` is now `.block-editor-plain-text` in 6.7.
this block didn't previously support in code any alignments other than default/centred, despite it declaring that it did in the block's settings. this has been fixed.

**Comment by jaymcp** [comment]
> Background Media BLOCK: does not render correctly and breaks when trying to add a BG image.

there were a few issues with the render that have been fixed.

**Comment by jaymcp** [comment]
> Background Media PATTERN: no top padding on column inner blocks (frontend)

these patterns have been modified.

**Comment by jaymcp** [comment]
> Buttons: Back link styles don't apply on the frontend, all buttons are pill shaped on the frontend. Default style when inserting button is off http://bigbite.im/i/6gwWem

Fixed in https://github.com/amnestywebsite/wp-plugin-amnesty-branding/pull/65

**Comment by jaymcp** [comment]
> Collapsable/Details: details styles appear to be part of this PR (compare to original PR https://github.com/amnestywebsite/humanity-theme/pull/240, but do not seem to be applying at all http://bigbite.im/i/1iSWPw)

Fixed in 9788d59

**Comment by jaymcp** [comment]
> Countdown Timer: inspector controls looking a little wonky http://bigbite.im/i/La52p2

this appears to be some weirdity with the block editor. shoehorned a fix in 8dfb808. this also adds missing block props.

**Comment by jaymcp** [comment]
> Custom card pattern: button expands outside the card in the editor, image covers, but image position might need addressing (http://bigbite.im/i/dkYtCB)

fixed in dcba3ca

**Comment by jaymcp** [comment]
> Resource Download: No padding on button, and block styles labelled incorrectly (http://bigbite.im/i/OejEbr), core/file is available in the block inserter, not sure if this should be hidden

fixed in https://github.com/amnestywebsite/wp-plugin-amnesty-branding/pull/66 and 136ed72

core/file has recently been enabled, so that's all good.

**Comment by jaymcp** [comment]
> Links with Icons Patterns: all buttons are justified to the left rather than the centre, square border style is missing, also has brand styles that I don't think belong on there (http://bigbite.im/i/bVwFgq)

this may have been fixed in an earlier commit, as i can't repro

**Comment by jaymcp** [comment]
> Regions: works as expected, but some changes are a step behind in the editor, namely changing taxonomy and subregions toggle

this is fixed in a445bbe. much of the data layer of the display component has been rewritten away from refs to state and effects.

**Comment by jaymcp** [comment]
> Related Content: block breaks as soon as it is inserted into a post

dedicated API call migrated to a new REST API field on the post object, so that we can use the entity record already retrieved in the component. in 34a1e54

**Comment by jaymcp** [comment]
> Slider block: block breaks as soon as it is inserted into a post

fixed in 864216a

**Comment by jaymcp** [comment]
> Tweet Action: alternative style has no effect in the editor, Size dropdown appears to have no effect anywhere.

fixed in 81f6f22

**Comment by jaymcp** [comment]
> Modal CTA: when opening the modal on the frontend, the entire contents of the dropdown is displayed (http://bigbite.im/i/k9qyLZ)

fixed in https://github.com/amnestywebsite/wp-plugin-theme-companion/pull/72

**Comment by jaymcp** [comment]
> Sidebar block: don't seem to be able to get the sidebar block to render on the front end

fixed in 94fea56

**Comment by jaymcp** [comment]
> Recipients block: dropdown displays over other content on the front end

fixed in https://github.com/amnestywebsite/wp-plugin-amnesty-branding/pull/67

**Comment by jaymcp** [comment]
> Blockquote: core quote still hidden and missing styles, previous PR for reference: https://github.com/amnestywebsite/humanity-theme/pull/326

nearly missed this one! fixed in https://github.com/amnestywebsite/wp-plugin-amnesty-branding/pull/64 and 28d3fb8

**Comment by Gentyspun** [comment]
- Background media BLOCK - content renders outside the background image
- core/quote - has 2 sets alignment controls, and without alignment black bar sometimes doesn't appear (usually if you change block style to plain and then back to default)
- Buttons - yellow button style has incorrect font colour when entering text and then has wrong colour border (editor only)
- LWI Patterns - still missing square borders
- Related content - Cannot seem to get RC to display on the front end, no matter how many terms I apply
- Slider - displays all slides in the editor (http://bigbite.im/i/P1myoV)
- iFrame Button: nothing happens when clicking the button on the frontend
- Sidebar block: don't seem to be able to get the sidebar block to render on the front end
- Recipients block: dropdown displays over other content on the front end (http://bigbite.im/i/ON9B2j)

**Comment by jaymcp** [comment]
i realise that the above comment is a wip, but i just wanted to check one thing:
> core/quote - has 2 sets alignment controls, and without alignment black bar sometimes doesn't appear (usually if you change block style to plain and then back to default)

is one of the sets of controls for the paragraph block that is within the quote block?

**Comment by Gentyspun** [comment]
> i realise that the above comment is a wip, but i just wanted to check one thing:
> 
> > core/quote - has 2 sets alignment controls, and without alignment black bar sometimes doesn't appear (usually if you change block style to plain and then back to default)
> 
> is one of the sets of controls for the paragraph block that is within the quote block?

Good question, they both appear when the quote is selected and both move the entire block (http://bigbite.im/i/7K8etB)

**Comment by jaymcp** [comment]
> > i realise that the above comment is a wip, but i just wanted to check one thing:
> > > core/quote - has 2 sets alignment controls, and without alignment black bar sometimes doesn't appear (usually if you change block style to plain and then back to default)
> > 
> > 
> > is one of the sets of controls for the paragraph block that is within the quote block?
> 
> Good question, they both appear when the quote is selected and both move the entire block (http://bigbite.im/i/7K8etB)

i think the first is block-level alignment, and the latter text-level alignment. add a citation and you should be able to see the difference in behaviour.

**Comment by Gentyspun** [comment]
> > > i realise that the above comment is a wip, but i just wanted to check one thing:
> > > > core/quote - has 2 sets alignment controls, and without alignment black bar sometimes doesn't appear (usually if you change block style to plain and then back to default)
> > > 
> > > 
> > > is one of the sets of controls for the paragraph block that is within the quote block?
> > 
> > 
> > Good question, they both appear when the quote is selected and both move the entire block (http://bigbite.im/i/7K8etB)
> 
> i think the first is block-level alignment, and the latter text-level alignment. add a citation and you should be able to see the difference in behaviour.

Ahhh yep, you're right, I see it. I've removed that particular issue from the list

**Comment by jaymcp** [comment]
> Background media BLOCK - content renders outside the background image (http://bigbite.im/i/mnQOzM)

fixed in ec76915

**Comment by jaymcp** [comment]
> core/quote - Without alignment black bar sometimes doesn't appear (usually if you change block style to plain and then back to default) (http://bigbite.im/i/7K8etB)

fixed in 27f9238

**Comment by jaymcp** [comment]
> Buttons - yellow button style has incorrect font colour when entering text and then has wrong colour border (editor only - http://bigbite.im/i/lXZCfU)

fixed in https://github.com/amnestywebsite/wp-plugin-amnesty-branding/pull/69

**Comment by jaymcp** [comment]
> LWI Patterns - still missing square borders (http://bigbite.im/v/xDSXAA)

fixed in 4800362

**Comment by jaymcp** [comment]
> Slider - displays all slides in the editor (http://bigbite.im/i/P1myoV)

fixed in fc5c5cf

**Comment by jaymcp** [comment]
> iFrame Button: nothing happens when clicking the button on the frontend

fixed in 9417dfa

**Comment by jaymcp** [comment]
> Sidebar block: don't seem to be able to get the sidebar block to render on the front end

i've hidden this from the inserter in 6e43f28. it really only exists to facilitate template setup

**Comment by jaymcp** [comment]
> Recipients block: dropdown displays over other content on the front end (http://bigbite.im/i/ON9B2j)

this is likely now fixed with the typo fix for the background colour of the dropdown?
